name: LocaVel
description: Local Travel App for Indonesian zone.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-126.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  google_maps_flutter: ^2.1.8
  google_maps_flutter_web: ^0.4.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
  fonts:
    - family: RockoFLF
      fonts:
        - asset: fonts/rockoflf.ttf
        - asset: fonts/rockoflf-bold.ttf
        - asset: fonts/rockoultraflf.ttf
        - asset: fonts/rockoultraflf-bold.ttf